spring:
  application:
    name: @name@
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
server:
  port: 8062
#eureka:
#  instance:
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
info:
  app.name: @name@
  jdk.version: @java.version@
  build.artifactId: @project.artifactId@
  build.version: @project.version@
management:
  endpoint:
    health:
      show-details: always
