server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12 # 启用http2
    key-store-password: 123456  # 证书密码
    key-store-type: PKCS12  # 证书类型
    protocol: TLSv1.2 # 协议类型
    key-alias: tsc-http2
spring:
  application:
    name: @name@
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
#eureka:
#  instance:
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    hostname: localhost
#    metadata-map:
#      profile: test
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
info:
  app.name: @name@
  jdk.version: @java.version@
  build.artifactId: @project.artifactId@
  build.version: @project.version@
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: false
